Update CI to use docker images
HoTT/HoTT pull request #1502
Opened 2021-04-29 21:49 UTC by Alizter

I've updated the CI to use docker images (basically precompiled versions of coq). I've gotten rid of the old build jobs that use the submodule. We only leave the quickdoc, html and dpdgraph together with alyectron.

The advantage of doing things like this is that we can build the library in around 4min!

In the future, we want the build jobs to upload their image as an artifact so that the documentation jobs can work directly with that. Something similar was suggested by Jason in https://github.com/HoTT/HoTT/issues/1388#issuecomment-826792147.

2021-04-29 21:54 UTC, Alizter commented on .github/workflows/ci.yml
> +## These are the tiggers for the CI to run
```suggestion
## These are the triggers for the CI to run
```

2021-04-29 21:55 UTC, Alizter commented on .github/workflows/ci.yml
> +        # We build on our supported version of coq and master
```suggestion
        # We build on our supported version of coq and the master version
```

2021-04-29 22:05 UTC, JasonGross commented
> I don't think it makes sense to try the dev version as that can be unstable.

No, part of the contract we must uphold to continue being tested on Coq's CI is to test against the tip of Coq master.  So we should test the dev version as well.

2021-04-29 22:10 UTC, Alizter commented on .github/workflows/ci.yml
> +        coq_version: [ '8.13' , 'latest' ]
```suggestion
        coq_version: [ '8.13' , 'latest' , 'dev' ]
```

2021-04-29 22:11 UTC, Alizter commented
@JasonGross OK fair enough, I've also added the dev version.

2021-04-29 22:13 UTC, JasonGross requested changes

2021-04-29 22:13 UTC, JasonGross commented on .github/workflows/ci.yml
> -          env: { VALIDATE: "yes"   , UPDATE_QUICK_DOC: "" }
Why'd you remove the validate target?

2021-04-29 22:13 UTC, JasonGross commented on .github/workflows/ci.yml
> +          etc/coq-scripts/github/reportify-coq.sh --errors make TIMED=1 -j2     --output-sync GH_REPORT_ERRORS=1
We should also pass `--warnings` iff we're building for Coq master.  And I think we don't want `GH_REPORT_ERRORS=1`
```suggestion
          etc/coq-scripts/github/reportify-coq.sh --stdout --errors ${{ matrix.extra_gh_reportify }} etc/coq-scripts/timing/make-pretty-timed.sh -j2 TIMING=1
          make
```

2021-04-29 22:13 UTC, JasonGross commented on .github/workflows/ci.yml
> +        ocaml_version: [ '4.11-flambda' ]
I think this will work?
```suggestion
        coq_version: [ '8.13' , 'latest' ]
        ocaml_version: [ '4.11-flambda' ]
        include:
        - coq_version: '8.13'
          extra_gh_reportify: '--warnings'
```

2021-04-29 22:17 UTC, JasonGross commented on .github/workflows/ci.yml
> +        ocaml_version: [ '4.11-flambda' ]
I think this will work?
```suggestion
        coq_version: [ '8.13' , 'latest' , 'dev' ]
        ocaml_version: [ '4.11-flambda' ]
        include:
        - coq_version: 'dev'
          extra_gh_reportify: '--warnings'
```

2021-04-29 22:21 UTC, Alizter commented on .github/workflows/ci.yml
> -          env: { VALIDATE: "yes"   , UPDATE_QUICK_DOC: "" }
Ah that wasn't intentional.

2021-04-29 22:22 UTC, Alizter commented on .github/workflows/ci.yml
> +
```suggestion
        - label: validate
          env: { VALIDATE: "yes"   , UPDATE_QUICK_DOC: "" }
```

2021-04-29 22:23 UTC, Alizter commented on .github/workflows/ci.yml
> -          env: { VALIDATE: "yes"   , UPDATE_QUICK_DOC: "" }
I've added it back in.

2021-04-29 22:37 UTC, jdchristensen commented
This seems like a nice approach!

2021-04-29 22:42 UTC, Alizter commented
@JasonGross What exactly does validate do?

2021-04-29 23:04 UTC, JasonGross commented
validate runs the .vo files through coqchk.  I like adding it to my jobs as a service to the coqdevs to give coqchk more coverage

2021-05-02 13:23 UTC, JasonGross approved these changes

2021-05-02 17:06 UTC, merged