Monoidal cat
HoTT/HoTT pull request #1648
Opened 2022-04-30 01:02 UTC by patrick-nicodemus

We define a monoidal category.

2022-05-01 23:19 UTC, patrick-nicodemus commented
@Alizter I am not experienced with git. Do you have a suggestion for how to resolve this issue?

2022-05-01 23:42 UTC, Alizter commented
Git merge has issues especially when submodules have been changed as in #1647. I suggest using a rebase, which more can be found here: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase.

If you do an interactive rebase `git rebase upstream/master` it should also get rid of those merge commits. You may need to do a `git fetch upstream` first though.

2022-05-02 19:18 UTC, patrick-nicodemus commented
I gave it another try but I might have screwed it up, I am not confident that I've done the rebase correctly. We will see when the CI runs.
(Does the CI run automatically on a regular basis or does it have to be triggered?)

2022-05-02 20:28 UTC, Alizter commented
@patrick-nicodemus Would you like me to force push to your branch directly so that I can clean up the history? I'll also mention what I am doing when I do it.

2022-05-02 20:29 UTC, Alizter commented
By the way, since you are a first time contributor, GitHub requests a manual acceptance to run the CI. But after this contribution, the CI should automatically run for every PR.

2022-05-02 23:04 UTC, patrick-nicodemus commented
> @patrick-nicodemus Would you like me to force push to your branch directly so that I can clean up the history? I'll also mention what I am doing when I do it.

Yeah, please. You can override anything that's in there, I have my own copies of the files.

I believe I somehow have an incorrect version of the .gitmodules file, I did a rebase on my local machine but the fork hosted on github may have problems with the file. I might do a hard reset of the github repo as well.

2022-05-03 10:04 UTC, Alizter commented
@patrick-nicodemus Hi, in order for me to push to your branch, you need to select a check box in the bottom right corner of this PR which says: allow commits from other maintainers or something similar like that.

I have a version of your changes with the commit history cleaned up. Unfortunately, multiple things seem to have gone wrong when you were rebasing/merging which caused this mess to appear. Nothing to worry about however!

Let me know when you have done that then I can push to your branch. :-)

2022-05-03 21:17 UTC, patrick-nicodemus commented
![image](https://user-images.githubusercontent.com/32827763/166567725-1d0969c9-edb0-4a7e-93c3-9b0b757adf6f.png)
Hi @Alizter ;
I've checked the given checkbox. I hope this is what was intended. Otherwise let me know and i'll look around for the right one.
I appreciate your patience in dealing with my lack of background with Git.

2022-05-03 21:19 UTC, patrick-nicodemus commented
I don't think it would be too bad for me to simply nuke the fork and start over with a new one if this becomes too much of a hassle.

2022-05-03 21:26 UTC, Alizter commented
@patrick-nicodemus I force pushed. Let me know if everything looks correct.

2022-05-03 21:28 UTC, Alizter commented
By the way, if you want to update your local branch to this one, you will have to do
```sh
git reset --hard origin/monoidal-cat
```
which will reset your commit on your local monoidal-cat branch to the one on your fork (which I force pushed too).

Sorry that this has been so complicated! It is usually not supposed to happen the first time :)

2022-05-03 21:31 UTC, patrick-nicodemus commented
@Alizter Thank you. I think the version of the commit that got pushed still has the git annotations in it though, so it's failing the build request. I can edit this on my end, hopefully?

2022-05-03 21:35 UTC, patrick-nicodemus commented
> By the way, if you want to update your local branch to this one, you will have to do
> 
> ```shell
> git reset --hard origin/monoidal-cat
> ```
> 
> which will reset your commit on your local monoidal-cat branch to the one on your fork (which I force pushed too).
> 
> Sorry that this has been so complicated! It is usually not supposed to happen the first time :)

Ok I missed this, sorry, I should have waited a minute.

2022-05-03 21:47 UTC, patrick-nicodemus commented
> By the way, if you want to update your local branch to this one, you will have to do
> 
> ```shell
> git reset --hard origin/monoidal-cat
> ```
> 
> which will reset your commit on your local monoidal-cat branch to the one on your fork (which I force pushed too).
> 
> Sorry that this has been so complicated! It is usually not supposed to happen the first time :)

So, I didn't read this comment before leaping into action and I did an ordinary push/pull between my local repo and the one hosted here. Is this going to screw things up?

Also, I understand how to enter the various commands you're talking about into my terminal to do a hard reset on my local repo or something like this, but I am a bit confused about how to get similarly fine grained control over the Github fork. I see basic pull and push options on the GUI but I'm clicking around on the website and I don't see the hard reset option. Googling around for "github hard reset" only takes me to git documentation on the CLI, which isn't what I want here.

2022-05-03 22:44 UTC, Alizter commented
When you force push a branch to a github repo, you will do a hard reset.

2022-05-03 22:45 UTC, Alizter commented
I force pushed the same branch I had again (which ended up dropping your extra commits) so it should all be fixed now.

2022-05-03 22:50 UTC, Alizter commented
I've gone ahead and removed the froms and extra whitespace too, at least it the CI will run now.

2022-05-13 01:01 UTC, mikeshulman commented
This looks fine to me, although I'm not an expert on the Categories sublibrary.  @JasonGross any thoughts?  I guess one question is whether we want to continue adding to the Categories sublibrary, since we're moving towards using the WildCat sublibrary in the rest of the library.

2022-05-13 07:14 UTC, JasonGross requested changes
Thanks for the contribution!

The funext needs to be moved to a section, everything else is just a suggestion.

I'm also curious how long this file takes to compile.  I seen to recall monoidal categories being slow when I tried them

2022-05-13 07:14 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
This makes a global funext axiom, you should instead wrap everything in a section

2022-05-13 07:14 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Local Infix "∘" := Functor.Composition.Core.compose.
I think we already have a Utf8 file that defines this?

2022-05-13 07:14 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Local Notation "A ⊗ B" := (tensor (A, B)) (at level 45).
It might be good to reserve this infix notation in the file that reserves all the notations

2022-05-13 07:14 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +    pentagon_eq_holds : forall a b c d : C, pentagon_eq alpha  a b c d;
```suggestion
    pentagon_eq_holds : forall a b c d : C, pentagon_eq alpha a b c d;
```

2022-05-13 07:14 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Definition pretensor (A : C) := Functor.Prod.Core.induced_snd tensor A.
You could just use `induced_snd tensor A`, I think.  Any reason for qualifying it?

2022-05-13 07:14 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Notation lambda_nat_trans := ((@morphism_isomorphic _ _ _) lambda).
You don't need the extra parentheses here.  Any reason to keep them?

2022-05-14 22:59 UTC, patrick-nicodemus commented
> This looks fine to me, although I'm not an expert on the Categories sublibrary. @JasonGross any thoughts? I guess one question is whether we want to continue adding to the Categories sublibrary, since we're moving towards using the WildCat sublibrary in the rest of the library.

Can you tell me a little bit about this shift? I will do whatever you folks want, I wasn't aware that such a shift was underway or intended.

I would like to know if you can provide links to some discussion of the purpose of this shift and what the advantages are of the Wildcat library. As much info as possible would be great, I don't want to continue in this direction if at some point in the near future the guidance will be that we don't want to add any more to this sublibrary.

2022-05-14 23:05 UTC, patrick-nicodemus commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
Because the definition of a monoidal category cannot be given without the funext axiom, do you think it is appropriate to use 
`Require Import Axioms.Funext.`

2022-05-14 23:07 UTC, patrick-nicodemus commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
I ran into some frustrating technical problems at one point due to code spread across multiple files calling on distinct instances of funext. Having a unique instance of funext would be helpful.

2022-05-14 23:39 UTC, patrick-nicodemus commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Local Infix "∘" := Functor.Composition.Core.compose.
Maybe you can suggest a good way to do this?

There are some overloaded notations, like \circ can mean morphism composition in a category or functor composition. Which one Coq interprets it as by default depends on the order in which the Utf8 files are required/imported, and/or the order in which the notation scopes are opened in which they're defined. I don't know how to say something like, "Let "\circ" be understood as in Functor.utf8" or "let \times be defined as in this notation scope", so I'm manually writing Local Infix "\circ" := Functor.Composition.Core.compose to make it clear that it this interpretation will take precedence over the one given in Category.Utf8. If I reversed the order in which they were imported I would have the same problem with some other command.

2022-05-15 00:23 UTC, patrick-nicodemus commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Definition pretensor (A : C) := Functor.Prod.Core.induced_snd tensor A.
Given the name scopes, NaturalTransformation.Prod.induced_snd is the default interpretation

2022-05-15 00:34 UTC, patrick-nicodemus commented
@JasonGross 
> Thanks for the contribution!
> 
> The funext needs to be moved to a section, everything else is just a suggestion.
> 
> I'm also curious how long this file takes to compile. I seen to recall monoidal categories being slow when I tried them
[MonoidalCategory.v.timing.txt](https://github.com/HoTT/HoTT/files/8694090/MonoidalCategory.v.timing.txt)

2022-05-15 01:09 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
> do you think it is appropriate to use `Require Import Axioms.Funext.`

No, you should insert `Section with_funext.` above this line and `End with_funext.` at the bottom of the file

2022-05-15 01:12 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Local Infix "∘" := Functor.Composition.Core.compose.
I believe you're looking for `Local Open Scope functor_scope` or `(...)%functor`.  The former says "prefer functor scope after this point", and the latter says "interpret `...` in functor scope".  You can do the same to get notations in other scopes, and should do this instead of redeclaring the notation without any scope.

2022-05-15 01:28 UTC, mikeshulman commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
I would be surprised if there isn't some way to define a monoidal category without funext.  Why do you say that?

2022-05-15 04:47 UTC, patrick-nicodemus commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
https://github.com/HoTT/HoTT/blob/master/theories/Categories/FunctorCategory/Morphisms.v
The NaturalIsomorphism type here assumes funext, this is what I used to define the associator and left/right unitors.

2022-05-15 05:16 UTC, patrick-nicodemus commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
We could just work with object-wise isomorphisms everywhere instead but it seems more elegant to be able to state that the pentagon equation and triangle equation hold in the category of functors and natural transformations.

2022-05-15 05:18 UTC, patrick-nicodemus commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Local Infix "∘" := Functor.Composition.Core.compose.
Ok, done.

2022-05-15 05:25 UTC, mikeshulman commented
I (or someone else) can write more about wildcats later, but one of their advantages is that they avoid funext by more or less working with a setoid equality on morphisms.

2022-05-15 08:36 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +Context `{Funext}.
More specifically, proving that functors forma category requires funext because the laws about composition only hold extensionally on the path parts of NTs.

2022-05-15 08:41 UTC, JasonGross approved these changes
LGTM modulo the removals I've suggested here, and assuming CI passes

2022-05-15 08:41 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Locate identity.
This seems leftover and should go
```suggestion
```

2022-05-15 08:41 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Local Notation "A ⊗ B" := (tensor (Datatypes.pair A B)) (at level 45, left associativity).
```suggestion
  Local Notation "A ⊗ B" := (tensor (Datatypes.pair A B)).
```

2022-05-15 08:41 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Locate identity.
```suggestion
```

2022-05-15 08:41 UTC, JasonGross commented on theories/Categories/Monoidal/MonoidalCategory.v
> +  Locate "1". Check (1%functor _).
```suggestion
```

2022-05-16 17:19 UTC, Alizter commented
Regarding wildcats, these are an "unbundled" approach to category theory. It was noticed a while back that much of category theory can be done without fully using all the data of a category. The most restrictive part of the data of a category is the truncatedness of the hom types. Wild cats allow you to do a lot of category theory by using Coq's typeclass search to assemble data about categories together. This has allowed us to apply categorical results to things that aren't strictly 1-categories.

A classic example is the category `Type` the arrows are functions and higher arrows homotopies. Somehow a wild cat is like an oo-cat without all the higher cells and all the coherence, but only as much as is needed for whatever it is that you are doing.

Regarding monoidal categories, your definition would work fine for hSets and vector spaces etc. But we also have our eyes on other kinds of monoidal categories such as pType. Here restricting the homs to sets would not allow us to say much about pType, but if we had a wild monoidal category, then lemmas about it would apply to both situations equally. FTR we have wild bicategories already in the WildCat/ folder and morally a monoidal category is just a "one object bicategory" (as a delooping). There are some practical formalizations reasons we might not define it this way though, and instead it would be better to have something like your development mixed with the wild category stuff.

2022-05-20 01:10 UTC, mikeshulman commented
After a side discussion with Patrick, I think it's fine to include this in the categories library.  It'd also be nice to have monoidal WildCats, but it sounds like for where he wants to go with it, the ordinary categories library may be easier.

2022-05-20 01:15 UTC, Alizter commented
I was perhaps a little too quick with my explanation of wildcats there. I should also say that I am completely fine with this PR. 0:-)

2022-05-23 09:13 UTC, Alizter approved these changes

2022-05-23 09:14 UTC, merged